export const CREATE_USER = "CREATE_USER";
export const LOG_IN = "LOG_IN";
export const GET_TOKEN = "GET_TOKEN";
export const GET_USER = "GET_USER";
export const GET_PHOTO_USER = "GET_PHOTO_USER";
export const POST_FOLLOW_NOTIFICATION = "POST_FOLLOW_NOTIFICATION";
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const POST_REEPLACER = "POST_REEPLACER";
// SEARCH BAR OPTIONS
export const GET_SONG_BY_NAME = "GET_SONG_BY_NAME";
export const GET_ALBUM_BY_NAME = "GET_ALBUM_BY_NAME";
export const GET_ARTIST_BY_NAME = "GET_ARTIST_BY_NAME";
export const GET_USER_BY_NAME = "GET_USER_BY_NAME";
export const CLEAR_DATA = "CLEAR_DATA";

//TOP 10 OPTIONS
export const GET_TOP_10_ALBUMS = "GET_TOP_10_ALBUMS";
export const GET_TOP_10_ARTISTS = "GET_TOP_10_ARTISTS";
export const GET_TOP_10_SONGS = "GET_TOP_10_SONGS";

// CRUD - POST
export const GET_ALL_POST = "GET_ALL_POST";
export const USER_NEW_POST = "USER_NEW_POST";
export const USER_UPDATE_POST = "USER_UPDATE_POST";
export const DELETE_POST = "DELETE_POST";
export const GET_OWN_POSTS = "GET_OWN_POSTS";
export const CHANGE_TYPE_OF_POST = "CHANGE_TYPE_OF_POST";

//DETAILS BY ID
export const GET_SONG_BY_ID = "GET_SONG_BY_ID";
export const GET_ARTIST_BY_ID = "GET_ARTIST_BY_ID";
export const GET_ALBUM_BY_ID = "GET_ALBUM_BY_ID";
export const CLEAR_DETAILS = "CLEAR_DETAILS";

//COMMENTS
export const GET_ALL_COMMENT = "GET_ALL_COMMENT";
export const USER_UPDATE_COMMENT = "USER_UPDATE_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const FALSE_ADDCOMENT = "FALSE_ADDCOMENT";
export const FALSE_ADDCOMENTPROFILE = "FALSE_ADDCOMENTPROFILE";

//FOLLOW
export const FOLLOW_USER = "FOLLOW_USER";
export const UNFOLLOW_USER = "UNFOLLOW_USER";
export const LIST_FOLLOWED = "LIST_FOLLOWED";
export const LIST_FOLLOWERS = "LIST_FOLLOWERS";
// LIKES
export const FALSE_LIKE = "FALSE_LIKE";
export const FALSE_DISLIKE = "FALSE_DISLIKE";

//ADMIN OPTIONS
export const BAN_USER = "BAN_USER";
export const UNBAN_USER = "UNBAN_USER";
export const GET_STATISTICS = "GET_STATISTICS";
export const GET_STANDARD_USERS = "GET_STANDARD_USERS";
export const GET_PREMIUM_USERS = "GET_PREMIUM_USERS";
export const GET_ARTIST_USERS = "GET_ARTIST_USERS";
export const GET_REPORTS = "GET_REPORTS";
export const GET_COMMENT_REPORTS = "GET_COMMENT_REPORTS";
export const GET_POST_REPORTS = "GET_POST_REPORTS";
export const GET_USER_REPORTS = "GET_USER_REPORTS";
export const GET_REPORT_BY_ID = "GET_REPORT_BY_ID";
export const ADMIN_DELETE_POST = "ADMIN_DELETE_POST";
export const ADMIN_ALLOW_POST = "ADMIN_ALLOW_POST";
export const ADMIN_DELETE_COMMENT = "ADMIN_DELETE_COMMENT";
export const ADMIN_ALLOW_COMMENT = "ADMIN_ALLOW_COMMENT";
export const CREATE_PLANS_PREMIUMS = "CREATE_PLANS_PREMIUMS";
export const DELETE_PLANS_PREMIUMS = "DELETE_PLANS_PREMIUMS";
export const MODIFY_PLANS_PREMIUMS = "MODIFY_PLANS_PREMIUMS";
export const GET_ALL_ADMIN_POSTS = "GET_ALL_ADMIN_POSTS";
export const CREATE_ADMIN_POST = "CREATE_ADMIN_POST";
export const DELETE_ADMIN_POST = "DELETE_ADMIN_POST";
export const EDIT_ADMIN_POST = "EDIT_ADMIN_POST";
export const GET_ALL_BANNED_USERS = "GET_ALL_BANNED_USERS";
export const GET_ALL_CAUSES_OF_REPORT = "GET_ALL_CAUSES_OF_REPORT";
export const GET_ALL_POSTS_USERS = "GET_ALL_POSTS_USERS";
export const GET_PREMIUM_PLANS = "GET_PREMIUM_PLANS";

//Recover Password
export const FORGOTTEN_PASSWORD_PRE = "FORGOTTEN_PASSWORD_PRE";
export const FORGOTTEN_PASSWORD_POST = "FORGOTTEN_PASSWORD_POST";

//Report

export const REPORT_COMMENT = "REPORT_COMMENT";
export const REPORT_USER = "REPORT_COMMENT";
export const REPORT_POST = "REPORT_COMMENT";

//Why Artist
export const WHY_ARTIST = "WHY_ARTIST";
